typography_spectrum: 0.9928043589693042
color:
  brandStrength: 0.9773203313196687
  lightness: 0.7235361386051788
  saturation: 0.5515716922335733
  rhythmicContrast: 0.17562584024651143
  brandColors:
    - '#00A6D0'
    - '#266D7F'
    - '#00FFFF'
    - '#0099CC'
    - '#00AAD5'
github: true
layout_spectrum: 0.42908220320303764
author:
  name: ''
  email: info@spotlessofutah.com
  url: 'http://www.spotlessofutah.com/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/740ffe38-6bf5-430f-a7de-78e510157456.png
name: Spotless of Utah
url: 'https://utahsjanitorialservice.com'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: About us
    url: 'https://www.spotlessofutah.com/about-us/'
    type: external
  - name: Contact us
    url: 'https://www.spotlessofutah.com/contact-us/'
    type: external
  - name: Jobs
    url: 'https://www.spotlessofutah.com/new-page/'
    type: external
  - name: Blog
    url: 'https://www.spotlessofutah.com/new-blog/'
    type: external
title: Commercial Cleaning  and Janitorial Services
content: []
description: >-
  Providing expert janitorial services in a local Utah area near you - Logan,
  Ogden, and Kaysville Utah Areas
purpose:
  - type: external
    label: Get a Quote
    url: 'https://www.spotlessofutah.com/quote/'
  - type: external
    url: 'https://www.spotlessofutah.com/cleaningservices/'
    label: Our Services
